name: anb-api
services:

  storeapi:
    build: 
      context: ./
      dockerfile: api.Dockerfile
    container_name: storeapi
    expose:
      - "80:8000"
    command: uvicorn storeapi.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    volumes:
      - ./:/app
      #- /mnt/storage/videos:/mnt/storage/videos

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"